type
  uint8_t* = char
  uint16_t* = uint16
  int16_t* = int16
  uint32_t* = uint32
  uint64_t* = uint64
  int32_t* = int32
  SOCKET_t* = uint32

type
  Socket* = ptr sSocket
  sSocket* = object
    fd*: SOCKET_t
    connectTimeout*: uint32
  
  ServerSocket* = ptr sServerSocket  
  sServerSocket* = object
    fd*: SOCKET_t
    backlog*: uint32
    
  HandleSet* = pointer # ptr sHandleSet
  ##sHandleSet* = object
  ##  handles*: fd_set
  ##  maxHandle : SOCKET_t

  Semaphore* = pointer
  #Thread* = pointer
  LinkedList* = pointer

##
## Set the maximum number of client connections
## 
const   
  CONFIG_CS104_MAX_CLIENT_CONNECTIONS* = 5 

## 
## Define the default size for the slave (outstation) message queue. This is used also
## to buffer ASDUs in the case when the connection is lost.
##
## For each queued message about 256 bytes of memory are required.
## 
const   
  CONFIG_CS104_MESSAGE_QUEUE_SIZE* = 100

## 
##  This is a connection specific ASDU queue for the slave (outstation). It is used for connection
##  specific ASDUs like those that are automatically generated by the stack or created in
##  the slave side callback. The messages in the queue are removed when the connection is lost.
##
##  For each queued message about 256 bytes of memory are required.
##
const
  CONFIG_CS104_MESSAGE_QUEUE_HIGH_PRIO_SIZE* = 50

## *
##  \brief This parameter restricts the k-buffer size when \ref CONFIG_CS104_SLAVE_POOL is enabled
##
##  The actual size of the k-buffer (corresponding to the APCI parameter k) is defined by the runtime parameter.
##  However the runtime parameter is restricted to the maximum of this value.
##

const
  CONFIG_CS104_MAX_K_BUFFER_SIZE* = 30